//
//  main.swift
//  002
//
//  Created by kkr on 8/28/16.
//  Copyright © 2016 allting. All rights reserved.
//

/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
 first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 even-valued terms.
 */

var fib = 0
var first = 0
var second = 1
var sum = 0

while fib < 4_000_000 {
    fib = first + second
    if fib % 2 == 0 {
        sum += fib
    }
    
    first = second
    second = fib
}

print("SUM: \(sum)")
